services:
    proxy:
        build:
            context: .
            target: proxy
        container_name: ${COMPOSE_PROJECT_NAME:-default}-proxy
        command:
            - '--api.insecure=true'
            - '--providers.docker=true'
            - '--entrypoints.web.address=:80'
            - '--entrypoints.websecure.address=:443'
            - '--entrypoints.websecure.http.tls=true'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 80:80
            - 8080:8080
            - 443:443
        networks:
            - laravel
        labels:
            - "traefik.enable=false"

    frontend:
        build:
            context: .
            target: frontend
        container_name: ${COMPOSE_PROJECT_NAME:-default}-frontend
        volumes:
            - ${VOLUME}/public:/code/public:cached
            - ${VOLUME}/storage/app/public:/code/public/storage:cached
        networks:
            - default
            - laravel
        depends_on:
            backend:
                condition: service_started
        labels:
            - "traefik.docker.network=laravel"
            - "traefik.http.routers.frontend.rule=Host(`${COMPOSE_PROJECT_NAME:-default}.localtest.me`)"
            - "traefik.http.routers.frontend.entrypoints=web,websecure"
            - "traefik.http.routers.frontend.priority=1"

    backend:
        build:
            context: .
            target: backend
        container_name: ${COMPOSE_PROJECT_NAME:-default}-backend
        volumes:
            - ${VOLUME}:/code:cached
        networks:
            - default
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
        labels:
            - "traefik.enable=false"

    worker:
        build:
            context: .
            target: artisan
        command: php artisan horizon
        container_name: ${COMPOSE_PROJECT_NAME:-default}-worker
        volumes:
            - ${VOLUME}:/code:cached
        networks:
            - default
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
            mailpit:
                condition: service_started
        labels:
            - "traefik.enable=false"

    scheduler:
        build:
            context: .
            target: artisan
        command: sh /usr/local/bin/scheduler
        container_name: ${COMPOSE_PROJECT_NAME:-default}-scheduler
        volumes:
            - ${VOLUME}:/code:cached
        networks:
            - default
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
            mailpit:
                condition: service_started
        labels:
            - "traefik.enable=false"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${COMPOSE_PROJECT_NAME:-default}-phpmyadmin
        networks:
            - default
            - laravel
        environment:
            PMA_HOST: mysql
            PMA_USER: laravel
            PMA_PASSWORD: laravel
        depends_on:
            mysql:
                condition: service_healthy
        labels:
            - "traefik.docker.network=laravel"
            - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${COMPOSE_PROJECT_NAME:-default}.localtest.me`)"
            - "traefik.http.routers.phpmyadmin.entrypoints=web"
            - "traefik.http.routers.phpmyadmin.priority=2"

    mysql:
        image: mysql:8.4
        container_name: ${COMPOSE_PROJECT_NAME:-default}-mysql
        command: ["mysqld", "--mysql-native-password=ON"]
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - default
        healthcheck:
            test: mysqladmin ping
        labels:
            - "traefik.enable=false"

    redis:
        image: redis:alpine
        container_name: ${COMPOSE_PROJECT_NAME:-default}-redis
        networks:
            - default
        healthcheck:
            test: redis-cli ping
        labels:
            - "traefik.enable=false"

    mailpit:
        image: axllent/mailpit:latest
        container_name: ${COMPOSE_PROJECT_NAME:-default}-mailpit
        networks:
            - default
            - laravel
        restart: unless-stopped
        volumes:
            - mailpit-data:/data
        ports:
            - 8025:8025 # web ui
            - 1025:1025 # smtp server
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        labels:
            - "traefik.docker.network=laravel"
            - "traefik.http.services.mailpit.loadbalancer.server.port=8025"
            - "traefik.http.routers.mailpit.rule=Host(`mailpit.${COMPOSE_PROJECT_NAME:-default}.localtest.me`)"
            - "traefik.http.routers.mailpit.priority=4"

volumes:
    mysql-data:
    mailpit-data:

networks:
    laravel:
        external: true
